/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/app/AppProvider.vue')['default']
    DialogContent: typeof import('./../components/app/DialogContent.vue')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    LoadingBarContent: typeof import('./../components/app/LoadingBarContent.vue')['default']
    MsgContent: typeof import('./../components/app/MsgContent.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NotificationContent: typeof import('./../components/app/NotificationContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SugonMap: typeof import('./../components/SugonMap.vue')['default']
    SugonNumber: typeof import('./../components/SugonNumber.vue')['default']
    SugonScrollTable: typeof import('./../components/SugonScrollTable.vue')['default']
    SugonVideo: typeof import('./../components/SugonVideo.vue')['default']
  }
}
